# lib/anchor.sh — opt-in Windows-side anchor that keeps the WSL distro
# session alive across "close PowerShell".
#
# WSL's per-distro lifecycle is gated on having at least one wsl.exe
# client attached. systemd=true keeps PID 1 running but doesn't anchor
# the distro session — closing the last client terminates the distro
# regardless of in-guest services, so gnome-shell-headless + grd (and
# the RDP listener) die with it. The lightweight VM itself stays alive
# (assuming vmIdleTimeout permits) but the distro inside is gone, which
# is what users actually feel as "WSL timed out and closed".
#
# This drops a tiny .vbs into the Windows user's Startup folder that
# launches a hidden `wsl.exe -d <distro> -- /usr/bin/sleep infinity`
# at logon. That hidden client holds the distro open until the user
# explicitly runs `wsl --shutdown` (which reclaims memory back to
# Windows) or logs out — in both cases the anchor re-fires on next
# Windows logon.
#
# Strictly opt-in. INSTALL_ANCHOR=1 to enable; default is 0. When
# INSTALL_ANCHOR=0 and a previously-installed anchor is present, the
# function removes the .vbs so toggling the option off cleanly disables
# persistence.

install_anchor() {
  ui_step "Distro persistence anchor"

  if ! command -v cmd.exe >/dev/null 2>&1; then
    ui_skip "cmd.exe not available (not WSL?) — skipping"
    return 0
  fi

  local distro="${WSL_DISTRO_NAME:-}"
  if [ -z "$distro" ]; then
    ui_warn "WSL_DISTRO_NAME unset — can't anchor a specific distro"
    return 0
  fi

  # Resolve %APPDATA% → Linux path. `cd /` first because Windows
  # binaries invoked via binfmt fail with "Invalid argument" when cwd
  # is under a dot-prefixed path (~/.local/share/...).
  local appdata_win appdata
  appdata_win=$(cd / && cmd.exe /c "echo %APPDATA%" 2>/dev/null | tr -d '\r')
  if [ -z "$appdata_win" ]; then
    ui_warn "couldn't resolve %APPDATA% — skipping"
    return 0
  fi
  appdata=$(wslpath -u "$appdata_win" 2>/dev/null) || {
    ui_warn "wslpath -u '$appdata_win' failed — skipping"
    return 0
  }

  local startup_dir="$appdata/Microsoft/Windows/Start Menu/Programs/Startup"
  local vbs="$startup_dir/wsl-${distro}-anchor.vbs"

  if [ "${INSTALL_ANCHOR:-0}" != "1" ]; then
    if [ -f "$vbs" ]; then
      rm -f "$vbs"
      ui_ok "Remove $vbs"
      ui_detail "anchor disabled — distro will terminate on last-client-close"
    else
      ui_skip "INSTALL_ANCHOR=0 (no anchor installed)"
    fi
    return 0
  fi

  mkdir -p "$startup_dir"

  local tmp
  tmp=$(mktemp)
  cat >"$tmp" <<EOF
' Generated by wsl-gnome-rdp-installer. Holds a hidden wsl.exe client
' attached to "$distro" so closing your launching shell doesn't kill
' the distro session (and with it gnome-shell-headless + grd / RDP).
' Run \`wsl --shutdown\` to reclaim memory; anchor re-fires on next
' Windows logon. Delete this file to disable persistence entirely.
Set sh = CreateObject("WScript.Shell")
sh.Run "wsl.exe -d $distro -- /usr/bin/sleep infinity", 0, False
EOF

  if [ -f "$vbs" ] && cmp -s "$vbs" "$tmp"; then
    rm -f "$tmp"
    ui_skip "no change needed"
    ui_detail "$vbs"
    return 0
  fi

  # cp + rm rather than `mv`: drvfs (/mnt/c) can't preserve owner /
  # timestamps the way ext4 does, and `mv` always tries — emitting a noisy
  # "Operation not permitted" pair of warnings even though the rename
  # itself succeeds. `cp` without -p doesn't try to preserve metadata, so
  # it's quiet on drvfs.
  cp -- "$tmp" "$vbs"
  rm -f "$tmp"
  ui_ok "Install $vbs"
  ui_detail "fires at next Windows logon — double-click in Explorer to start now"
}
