# lib/cgroup_collision.sh — detect & resolve WSL2 multi-distro cgroup
# collision on /user.slice/user-$UID.slice/user@$UID.service/.
#
# WSL2 doesn't cgroup-namespace its distros: every distro shares the
# utility VM's kernel and the same /sys/fs/cgroup tree. Two distros that
# both expose a UID-N user therefore have their PID-1 systemds targeting
# the same cgroup path. Whichever boots second sees subtree_control
# already populated by the first and user@$UID.service fails to start:
#
#     Failed to spawn executor: Device or resource busy
#     user@$UID.service: Failed with result 'resources'.
#
# Distinct from systemd #41278 — the drop-in in dbus.sh can't help
# because the foreign tenant in the cgroup is *live*, not stale.
#
# Detection signal: cgroup.procs entries from a foreign PID namespace
# read as `0` from inside this distro. A cgroup that contains processes
# but only PID-0 lines proves another distro owns it.

NEW_UID_START="${NEW_UID_START:-1001}"

# Pick the smallest unused UID >= NEW_UID_START, considering BOTH:
#   - /etc/passwd entries on this distro (getent passwd)
#   - the shared WSL2 cgroup tree (/sys/fs/cgroup/user.slice/user-N.slice/),
#     which reflects any UID used by a user@N.service in *any* live distro.
# That second check is what protects against a third distro also using 1001
# (or any future N): we'll skip past it and pick the next truly free UID.
pick_next_free_uid() {
  local n="${1:-$NEW_UID_START}"
  local cgroup_base="/sys/fs/cgroup/user.slice"
  while :; do
    if getent passwd "$n" >/dev/null 2>&1; then n=$((n+1)); continue; fi
    if [ -d "$cgroup_base/user-${n}.slice" ] \
       || [ -d "$cgroup_base/user-${n}.slice/user@${n}.service" ]; then
      n=$((n+1)); continue
    fi
    printf '%s\n' "$n"
    return 0
  done
}

# 0 = foreign tenant detected, 1 = clean (or path doesn't exist yet).
#
# The kernel reports PIDs from foreign PID namespaces as `0` in cgroup.procs,
# so any `^0$` line anywhere under our user@$UID.service cgroup proves another
# distro is using it. We must NOT require *all* lines to be `0`: on a fresh
# distro that's already been launched (WSL tries `systemd --user` for the new
# user immediately and that attempt leaves PIDs behind), the cgroup contains
# both the failed-local PIDs (non-zero) and the foreign tenant's PIDs (zero).
detect_cgroup_collision() {
  local UID_NUM
  UID_NUM=$(id -u)
  local base="/sys/fs/cgroup/user.slice/user-${UID_NUM}.slice/user@${UID_NUM}.service"
  [ -d "$base" ] || return 1
  if find "$base" -name cgroup.procs -print0 2>/dev/null \
     | xargs -0 -r grep -l '^0$' 2>/dev/null \
     | grep -q .; then
    return 0
  fi
  return 1
}

# Install a oneshot system unit that renumbers $USERNAME at the next boot,
# before user.slice is started. We can't safely renumber inline because the
# installer's own shell is owned by the current UID — but at early boot,
# before login + before user@.service, no user processes exist yet.
stage_uid_renumber() {
  local NEW_UID="${1:-$(pick_next_free_uid)}"
  # Default GID matches NEW_UID (systemd convention; matches how WSL provisions
  # the default user). Caller can override.
  local NEW_GID="${2:-$NEW_UID}"
  local UID_NUM GID_NUM USERNAME
  UID_NUM=$(id -u)
  GID_NUM=$(id -g)
  USERNAME=$(id -un)
  local UNIT="/etc/systemd/system/wsl-renumber-uid.service"
  local SCRIPT="/usr/local/sbin/wsl-renumber-uid.sh"

  ui_step "Stage UID renumber"
  ui_detail "$USERNAME ($UID_NUM → $NEW_UID, gid $GID_NUM → $NEW_GID)"

  sudo install -d -m 755 /usr/local/sbin
  sudo tee "$SCRIPT" >/dev/null <<EOF
#!/usr/bin/env bash
# Auto-generated by wsl-gnome-rdp-installer. Renumbers $USERNAME from
# UID $UID_NUM/GID $GID_NUM to UID $NEW_UID/GID $NEW_GID, then disables
# itself. Runs before user.slice on early boot so no user processes are
# live to block usermod.
set -euo pipefail
exec >/var/log/wsl-renumber-uid.log 2>&1
echo "[\$(date -Is)] Renumbering $USERNAME: $UID_NUM -> $NEW_UID, $GID_NUM -> $NEW_GID"

if pgrep -u $UID_NUM -a >/dev/null 2>&1; then
  echo "Refusing: UID $UID_NUM has live processes — unit ran too late."
  exit 1
fi

groupmod -g $NEW_GID $USERNAME
usermod  -u $NEW_UID -g $NEW_GID $USERNAME

# Chown everything UID/GID $UID_NUM/$GID_NUM below /, but skip foreign mounts
# (Windows DrvFs at /mnt, kernel virtual fs, runtime).
find / \\
  -path /mnt -prune -o \\
  -path /proc -prune -o \\
  -path /sys -prune -o \\
  -path /dev -prune -o \\
  -path /run -prune -o \\
  \\( -uid $UID_NUM -o -gid $GID_NUM \\) -print0 \\
  | xargs -0 -r chown -h $NEW_UID:$NEW_GID || true

systemctl disable wsl-renumber-uid.service || true
rm -f "$UNIT" "$SCRIPT"
echo "[\$(date -Is)] Renumber complete."
EOF
  sudo chmod 755 "$SCRIPT"

  sudo tee "$UNIT" >/dev/null <<EOF
[Unit]
Description=Renumber WSL user UID to avoid multi-distro cgroup collision
DefaultDependencies=no
Before=user.slice systemd-user-sessions.service
After=local-fs.target
ConditionPathExists=$SCRIPT

[Service]
Type=oneshot
ExecStart=$SCRIPT
RemainAfterExit=no

[Install]
WantedBy=sysinit.target
EOF
  ui_spin "Install + enable wsl-renumber-uid.service" bash -c '
    set -e
    sudo systemctl daemon-reload
    sudo systemctl enable wsl-renumber-uid.service
  '

  # The WSL launcher caches the default user's UID in the Windows registry
  # at install time (HKCU\...\Lxss\<GUID>\DefaultUid). After the renumber,
  # `wsl -d <distro>` would call getpwuid(OLD_UID) → fail → drop the user
  # to a root shell. Setting [user]default=NAME in /etc/wsl.conf makes the
  # launcher resolve by name at boot instead, which is renumber-proof.
  ensure_wsl_conf_default_user "$USERNAME"
}

# Idempotently ensure /etc/wsl.conf has [user]default=$USERNAME. Three cases:
#   1. Already correct → no-op (re-runs are safe).
#   2. [user] section exists but no matching default= → warn, leave alone
#      (don't try to merge into a config the user is hand-managing).
#   3. No [user] section → append one.
ensure_wsl_conf_default_user() {
  local USERNAME="$1"
  local CONF=/etc/wsl.conf

  if [ -f "$CONF" ] \
     && sudo grep -qE "^[[:space:]]*default[[:space:]]*=[[:space:]]*${USERNAME}[[:space:]]*$" "$CONF"; then
    ui_skip "/etc/wsl.conf already declares default=${USERNAME}"
    return 0
  fi

  if [ -f "$CONF" ] \
     && sudo grep -qE '^[[:space:]]*\[user\][[:space:]]*$' "$CONF"; then
    ui_warn "/etc/wsl.conf has a [user] section but no 'default=${USERNAME}'"
    ui_detail "add it manually before 'wsl.exe -t ${WSL_DISTRO_NAME:-this distro}'"
    ui_detail "otherwise the launcher uses the old cached UID and drops you to root"
    return 0
  fi

  sudo install -d -m 755 /etc
  sudo tee -a "$CONF" >/dev/null <<EOF

[user]
default=${USERNAME}
EOF
  ui_ok "Append [user]default=${USERNAME} to /etc/wsl.conf"
}

# Front-end: detect collision, prompt, stage renumber if chosen.
# Called from install.sh BEFORE precheck_user_at_service, since the
# cgroup-fix drop-in there can't paper over a live foreign tenant.
precheck_cgroup_collision() {
  local UID_NUM
  UID_NUM=$(id -u)
  detect_cgroup_collision || return 0

  local distro="${WSL_DISTRO_NAME:-<this distro>}"
  local NEW_UID
  NEW_UID="$(pick_next_free_uid)"

  ui_step "Multi-distro cgroup collision detected"
  ui_warn "Another WSL2 distro is using /user.slice/user-${UID_NUM}.slice/user@${UID_NUM}.service/"
  ui_detail "user@${UID_NUM}.service in this distro cannot start until that's resolved"
  echo
  echo "Options:"
  echo "  1) Renumber this user to UID ${NEW_UID} now (recommended, permanent)."
  echo "     UID ${NEW_UID} is free both in /etc/passwd and across all live"
  echo "     WSL2 distros' cgroup tree (checked just now)."
  echo "     This will:"
  echo "       a. install a oneshot systemd unit that runs the actual"
  echo "          usermod/groupmod/chown at next boot (before login),"
  echo "       b. add [user]default=$(id -un) to /etc/wsl.conf so the WSL"
  echo "          launcher resolves your user by name, not the cached UID"
  echo "          (without this, you'd land in a root shell after reboot)."
  echo "     Then 'wsl.exe -t ${distro}' from Windows to trigger it, and"
  echo "     re-run this installer."
  echo "  2) Shut down the other distro from Windows now ('wsl.exe --shutdown'),"
  echo "     reopen this distro, and re-run."
  echo "  3) Continue anyway (RDP session won't come up; for diagnostic use)."
  echo
  local choice=""
  read -r -p "Choose [1/2/3]: " choice
  case "$choice" in
    1)
      stage_uid_renumber "$NEW_UID" "$NEW_UID"
      cat <<EOF

Renumber staged. /etc/wsl.conf updated with [user]default=$(id -un).
To complete:
  1. From a Windows shell:   wsl.exe -t ${distro}
  2. Reopen this distro from Windows Terminal — you'll land as $(id -un)
     at the new UID, NOT in a root shell.
  3. The renumber unit runs automatically on early boot, then disables
     and removes itself. Log: /var/log/wsl-renumber-uid.log
  4. Re-run this installer.
EOF
      exit 0
      ;;
    2)
      die "Run 'wsl.exe --shutdown' from Windows, reopen this distro, and re-run."
      ;;
    3)
      ui_warn "Continuing despite collision; user@${UID_NUM}.service will fail."
      ;;
    *)
      die "No valid choice made; aborting."
      ;;
  esac
}
