# lib/configure.sh — grdctl settings + systemd user units.

configure_grd() {
  ui_step "Configure gnome-remote-desktop"
  ui_detail "port $RDP_PORT"
  # Note: FreeRDP prints "[ERROR] x509_utils_from_pem: BIO_new failed for
  # certificate" during these calls — that line is benign noise from FreeRDP's
  # auth path probing; the dconf settings are still written.
  ui_spin "Set TLS cert/key + port + enable RDP" bash -c '
    set -e
    grdctl --headless rdp set-tls-cert "'"$TLS_DIR"'/rdp.crt"
    grdctl --headless rdp set-tls-key  "'"$TLS_DIR"'/rdp.key"
    if [ "'"${REUSE_CREDS:-0}"'" = "0" ]; then
      grdctl --headless rdp set-credentials "'"$RDP_USERNAME"'" "'"$RDP_PASSWORD"'"
    fi
    grdctl --headless rdp set-port "'"$RDP_PORT"'"
    grdctl --headless rdp disable-port-negotiation
    grdctl --headless rdp enable
  '
}

install_user_environment() {
  # systemd --user reads ~/.config/environment.d/*.conf at start and exports
  # those vars to every user service + dbus-activated app. We use this for
  # two things gnome-session would normally export but doesn't here (we run
  # gnome-shell standalone with --mode=user):
  #   10-wsl-gpu.conf       — GALLIUM_DRIVER so client apps render on the
  #                           GPU (d3d12) instead of falling through to
  #                           llvmpipe — except on Intel iGPUs (Meteor Lake
  #                           Arc Xe) where the d3d12 path renders broken
  #                           surfaces; pick_gallium_driver swaps to
  #                           llvmpipe there. The compositor unit's
  #                           drop-in is kept in sync.
  #   20-gnome-session.conf — XDG_CURRENT_DESKTOP/SESSION_TYPE so apps that
  #                           gate on the desktop name (gnome-control-center,
  #                           gnome-software, portals) actually launch.
  ui_step "User environment overrides"
  local target_dir="$HOME/.config/environment.d"
  mkdir -p "$target_dir"

  local gallium gsk
  gallium="$(pick_gallium_driver)"
  gsk="$(pick_gsk_renderer)"

  for src in "$PROJECT_ROOT"/environment.d/*.conf; do
    local base
    base="$(basename "$src")"
    if [ "$base" = "10-wsl-gpu.conf" ]; then
      # Generated, not copied: the value of GALLIUM_DRIVER depends on the
      # detected host GPU (see pick_gallium_driver in lib/common.sh).
      # GSK_RENDERER is conditionally emitted on hosts where GTK 4's
      # default (Vulkan via Mesa dzn) is broken — currently Intel Arc Xe.
      {
        cat <<EOF
# Generated by install.sh.
#
# Mesa OpenGL driver. d3d12 = Mesa→D3D12→DXG→host driver (hardware,
# verified on NVIDIA); llvmpipe = software rasterizer. Falls back to
# llvmpipe on Intel Arc Xe / Meteor Lake where the d3d12 EGL path
# produces broken surfaces. Override with WSL_RDP_GALLIUM_DRIVER.
GALLIUM_DRIVER=$gallium
EOF
        if [ -n "$gsk" ]; then
          cat <<EOF

# GTK 4 renderer. GTK 4.20+ prefers Vulkan; on WSL2 the only Vulkan
# implementation is Mesa's dzn (Vulkan-on-DX12), which Mesa itself
# flags as 'not a conformant Vulkan implementation, testing use only'
# — and on Intel Arc Xe / Meteor Lake it crashes GTK 4 apps (Nautilus
# hits VK_ERROR_DEVICE_LOST + SIGABRT within seconds). Pinning to
# '$gsk' on Intel keeps GTK 4 on Mesa's GL stack. NVIDIA/AMD are left
# unset — dzn Vulkan is stable there. Override with WSL_RDP_GSK_RENDERER.
GSK_RENDERER=$gsk
EOF
        fi
      } > "$target_dir/$base"
    else
      install -m 644 "$src" "$target_dir/$base"
    fi
  done
  ui_ok "Install environment.d/*.conf"
  ui_detail "$target_dir (gallium: $gallium${gsk:+, gsk: $gsk})"
  # Push into the already-running user manager so the change takes effect
  # without a logout. New dbus activations and `systemctl --user start`s pick
  # this up immediately; apps already running keep their old env until
  # restarted.
  if [ -n "$gsk" ]; then
    ui_spin "Push env into running user manager" \
      systemctl --user set-environment \
        "GALLIUM_DRIVER=$gallium" \
        "GSK_RENDERER=$gsk" \
        GDK_BACKEND=wayland \
        XDG_CURRENT_DESKTOP=GNOME \
        XDG_SESSION_TYPE=wayland
  else
    # On NVIDIA/AMD: don't set GSK_RENDERER (let GTK pick Vulkan). Also
    # unset any GSK_RENDERER left over from a previous Intel-detected
    # install so re-running on a transplanted distro doesn't pin the
    # value.
    ui_spin "Push env into running user manager" bash -c "
      systemctl --user set-environment \
        'GALLIUM_DRIVER=$gallium' \
        GDK_BACKEND=wayland \
        XDG_CURRENT_DESKTOP=GNOME \
        XDG_SESSION_TYPE=wayland
      systemctl --user unset-environment GSK_RENDERER 2>/dev/null || true
    "
  fi
}

install_default_wallpaper() {
  # Drop in the project's wallpaper as the first-run default. Only sets
  # gsettings when we haven't done so before (marker at
  # ~/.local/share/wsl-gnome-rdp-installer/.wallpaper-set), so a user
  # who chose their own wallpaper after the first install isn't
  # overridden every install.sh re-run. The image itself is still
  # refreshed in /usr/share/backgrounds so it survives image bumps.
  ui_step "Default wallpaper"
  local src="$PROJECT_ROOT/assets/pane-wallpaper.jpg"
  local dst=/usr/share/backgrounds/pane-wallpaper.jpg
  if [ ! -f "$src" ]; then
    ui_skip "no asset/pane-wallpaper.jpg in project dir"
    return 0
  fi
  if [ -f "$dst" ] && cmp -s "$src" "$dst"; then
    ui_skip "$dst already current"
  else
    ui_spin "Install $dst" \
      sudo install -D -m 644 "$src" "$dst"
  fi
  if ! command -v gsettings >/dev/null 2>&1; then
    ui_skip "gsettings unavailable; skipping desktop binding"
    return 0
  fi
  local marker="$HOME/.local/share/wsl-gnome-rdp-installer/.wallpaper-set"
  if [ -f "$marker" ]; then
    ui_skip "already bound (marker exists; preserving user's choice)"
    return 0
  fi
  install -d "$(dirname "$marker")"
  gsettings set org.gnome.desktop.background picture-uri      "file://$dst"
  gsettings set org.gnome.desktop.background picture-uri-dark "file://$dst"
  gsettings set org.gnome.desktop.background picture-options  zoom
  : > "$marker"
  ui_ok "Set as desktop background"
  ui_detail "$dst (zoom)"
}

install_xdg_user_dirs() {
  # Standard ~/Downloads, ~/Documents, ~/Pictures, ~/Music, ~/Videos,
  # ~/Desktop, ~/Templates, ~/Public. On a normal GNOME box these are
  # created by `xdg-user-dirs-update` running from
  # /etc/xdg/autostart/xdg-user-dirs.desktop at gnome-session start.
  # We don't run gnome-session here (`gnome-shell --mode=user` directly),
  # so the autostart entry never fires and the dirs never appear — file
  # dialogs get a flat $HOME with .config/.cache/.local visible, and
  # Nautilus's sidebar drops the Documents/Music/Pictures/Videos
  # entries because it gates them on user-dirs.dirs lines.
  #
  # We don't trust a bare `xdg-user-dirs-update` call here: it only
  # initialises user-dirs.dirs on first run and won't backfill missing
  # entries on subsequent runs. Past installs that bailed out early
  # (e.g., before the gnome-session autostart fired) leave a partial
  # file with just DESKTOP/DOWNLOAD/TEMPLATES — those re-runs of the
  # installer's old idempotency guard would skip on "Downloads exists"
  # and never fix the gap. Iterate explicitly with --set to force the
  # full set into place; --set is idempotent on its own line.
  ui_step "XDG user dirs"
  if ! command -v xdg-user-dirs-update >/dev/null 2>&1; then
    ui_skip "xdg-user-dirs-update not installed"
    return 0
  fi
  for pair in DESKTOP:Desktop DOWNLOAD:Downloads DOCUMENTS:Documents \
              MUSIC:Music PICTURES:Pictures VIDEOS:Videos \
              TEMPLATES:Templates PUBLICSHARE:Public; do
    name=${pair%:*}
    dir=${pair#*:}
    mkdir -p "$HOME/$dir"
    xdg-user-dirs-update --set "$name" "$HOME/$dir" 2>/dev/null || true
  done
  ui_ok "user-dirs.dirs"
  ui_detail "Downloads, Documents, Pictures, Music, Videos, Desktop, Templates, Public"
}

install_projects_dir() {
  # Populate Nautilus's sidebar via ~/.config/gtk-3.0/bookmarks
  # (still the canonical path under GTK4 — gtk-4.0 is settings only).
  # Two reasons we don't just rely on the XDG user-dirs mechanism:
  #
  #   1. Nautilus 50.1 stopped showing the XDG dirs (Documents,
  #      Downloads, Music, Pictures, Videos) in the sidebar by default.
  #      They resolve correctly via GLib (xdg-user-dir, GUserDirectory)
  #      but the sidebar only shows Home + bookmarks. Confirmed on
  #      gnome-50/Fedora 44.
  #   2. We want a ~/Projects entry too, which isn't a standard XDG
  #      dir at all.
  #
  # Fix both with a single explicit bookmarks file. Each line is a
  # URI optionally followed by a display name; without a name,
  # Nautilus uses the directory's basename. Ordering in the file is
  # the rendering order in the sidebar.
  ui_step "Nautilus sidebar bookmarks"
  mkdir -p "$HOME/Projects"
  local bookmarks="$HOME/.config/gtk-3.0/bookmarks"
  mkdir -p "$(dirname "$bookmarks")"
  {
    for d in Documents Downloads Music Pictures Videos; do
      [ -d "$HOME/$d" ] && printf 'file://%s/%s\n' "$HOME" "$d"
    done
    printf 'file://%s/Projects Projects\n' "$HOME"
  } > "$bookmarks"
  ui_ok "$bookmarks"
  ui_detail "Documents, Downloads, Music, Pictures, Videos, Projects"
}

enable_appindicator_extension() {
  ui_step "AppIndicator extension"
  # Add the AppIndicator/KStatusNotifierItem extension to the user's
  # `enabled-extensions` list. Without it gnome-shell exposes no system
  # tray (no StatusNotifierWatcher on the session bus); apps whose UI is
  # tray-icon-driven — jetbrains-toolbox is the headline example — refuse
  # to keep their main loop alive and exit silently after a feed refresh
  # ("Application shutdown as nothing keeps us alive" in toolbox.log).
  # The extension is installed system-wide by gnome-shell-extension-appindicator
  # in install_packages. We just need to enable it.
  #
  # We write directly via gsettings rather than `gnome-extensions enable`
  # because the latter requires gnome-shell to be running and to have
  # already scanned the extension dir; gsettings/dconf is unaffected by
  # shell state and the shell picks up the value on next start.
  local uuid='appindicatorsupport@rgcjonas.gmail.com'
  local current
  current="$(gsettings get org.gnome.shell enabled-extensions 2>/dev/null || echo '@as []')"
  case "$current" in
    *"$uuid"*)
      ui_skip "already enabled"
      return 0
      ;;
  esac
  if [ "$current" = "@as []" ] || [ "$current" = "[]" ]; then
    gsettings set org.gnome.shell enabled-extensions "['$uuid']"
  else
    # current looks like `['ext1@…', 'ext2@…']` — splice the new UUID in
    # before the closing bracket so we don't clobber any other enabled ones
    # (Pop Shell, etc.).
    gsettings set org.gnome.shell enabled-extensions "${current%]}, '$uuid']"
  fi
  ui_ok "Enable AppIndicator"
  ui_detail "takes effect on next gnome-shell start"
}

apply_flatpak_sync() {
  # Re-fire wsl-flatpak-wslg-sync now that install_packages has just
  # `flatpak install`-ed Firefox + ONLYOFFICE. wsl-qol's
  # initial_flatpak_sync_run runs early in bootstrap_wsl_qol — that's
  # intentional, before our dnf step uses the flatpak base setup. But
  # at that point ~/.local/share/flatpak/exports is empty, the
  # initial run finds nothing, and the .timer's OnUnitActiveSec=1min
  # only starts ticking from a service activation. Kicking the unit
  # again here both publishes the new flatpaks to /usr/share +
  # Start-Menu immediately and re-arms the periodic timer.
  ui_step "Flatpak → /usr/share sync (post-packages re-fire)"
  if ! systemctl --user list-unit-files wsl-flatpak-wslg-sync.service \
       >/dev/null 2>&1; then
    ui_skip "wsl-flatpak-wslg-sync.service not installed (QOL_FLATPAK_SYNC disabled?)"
    return 0
  fi
  ui_spin "wsl-flatpak-wslg-sync.service" \
    systemctl --user start --wait wsl-flatpak-wslg-sync.service
}

apply_theme_sync() {
  # Re-fire wsl-theme-sync now that the GNOME stack (and its gsettings
  # schemas) are installed. wsl-qol's own oneshot_theme_sync runs early
  # in bootstrap_wsl_qol — that's intentional, so the binfmt drop-in,
  # flatpak setup, and pulse-detach unit are ready before our dnf step
  # uses them. But it means the FIRST fire of wsl-theme-sync happens
  # before org.gnome.desktop.interface is registered: tier 1 (gsettings)
  # silently no-ops and color-scheme stays at its dconf default. wsl-qol
  # detects schema-missing and skips the fire there; we own the post-
  # packages re-fire. Idempotent — wsl-theme-sync is a one-shot mirror,
  # not a config writer.
  ui_step "Theme sync (post-packages re-fire)"
  if [ ! -x /usr/local/bin/wsl-theme-sync ]; then
    ui_skip "wsl-theme-sync not installed (QOL_THEME_SYNC disabled?)"
    return 0
  fi
  ui_spin "wsl-theme-sync (one-shot mirror)" \
    /usr/local/bin/wsl-theme-sync
}

install_dri_udev_rule() {
  ui_step "DRI device group ownership (WSL2 udev fix)"
  # The kernel hands /dev/dri/card* and /dev/dri/renderD* to udev with
  # default GIDs (39, 108, …). On Fedora those numbers map to `video`
  # / `render` and things "just work". On Ubuntu they map to unrelated
  # groups (`irc`, `netdev`), so the `video`/`render` users wsl-qol
  # adds dylan to can't open the device — libEGL gets Permission
  # denied, mutter falls back to swrast, and the RDP session runs at
  # software-rasterizer speed. Drop a udev rule that pins the canonical
  # group names regardless of distro.
  ui_spin "Install + reload /etc/udev/rules.d/99-wsl-dri.rules" bash -c '
    set -e
    sudo install -m 644 "'"$PROJECT_ROOT"'/extras/wsl-dri-udev.rules" \
                         /etc/udev/rules.d/99-wsl-dri.rules
    sudo udevadm control --reload
    sudo udevadm trigger --subsystem-match=drm
  '
  # `udevadm trigger` reapplies the rule on existing nodes, but on
  # WSL2 the trigger doesn't always re-chown — the dxg-backed devices
  # are quirky. Apply the change directly too so gnome-shell-headless
  # finds the correct ownership when install_systemd_units starts it
  # below.
  ui_spin "Apply group ownership to current /dev/dri/* nodes" bash -c '
    sudo chgrp video /dev/dri/card[0-9]* 2>/dev/null || true
    sudo chgrp render /dev/dri/renderD[0-9]* 2>/dev/null || true
  '
}

install_x11_unix_fix() {
  ui_step "WSLg /tmp/.X11-unix fix"
  # WSLg shadows /tmp/.X11-unix on every boot — as a symlink to
  # /mnt/wslg/.X11-unix on older builds, or as a read-only tmpfs
  # (sometimes stacked twice) on Ubuntu 26.04+. Mutter's Xwayland
  # rejects both layouts: the symlink fails its sticky-bit check, the
  # ro tmpfs fails its is-writable check. Once Xwayland fails,
  # gnome-shell-headless falls into a SIGABRT restart loop and the RDP
  # session is dead — codeberg #2. Ship a system-level oneshot whose
  # helper peels off whichever layout WSLg put down, lays down a real
  # mode-1777 directory in its place, and re-symlinks WSLg's X0 inside
  # (so DISPLAY=:0 still reaches the host X server).
  ui_spin "Install + enable wslg-x11-unix-fix.service" bash -c '
    set -e
    sudo install -m 755 "'"$PROJECT_ROOT"'/units/wslg-x11-unix-fix.sh" \
                         /usr/local/bin/wslg-x11-unix-fix
    sudo install -m 644 "'"$PROJECT_ROOT"'/units/wslg-x11-unix-fix.service" \
                         /etc/systemd/system/wslg-x11-unix-fix.service
    sudo systemctl daemon-reload
    sudo systemctl enable wslg-x11-unix-fix.service
  '
  # The helper is idempotent — always run after install so this
  # boot's WSLg layout gets fixed without waiting for the next
  # reboot. Important on first install: gnome-shell-headless is
  # about to start as part of install_systemd_units below, and it
  # SIGABRTs immediately if /tmp/.X11-unix isn't writable yet.
  ui_spin "Run wslg-x11-unix-fix.service now" \
    sudo systemctl start wslg-x11-unix-fix.service
}

install_systemd_units() {
  ui_step "User systemd units"
  mkdir -p "$SYSTEMD_USER_DIR" \
           "$SYSTEMD_USER_DIR/gnome-remote-desktop-headless.service.d" \
           "$SYSTEMD_USER_DIR/gnome-shell-headless.service.d"

  install -m 644 "$PROJECT_ROOT/units/gnome-shell-headless.service" \
                 "$SYSTEMD_USER_DIR/gnome-shell-headless.service"

  install -m 644 "$PROJECT_ROOT/units/gnome-remote-desktop-headless.override.conf" \
                 "$SYSTEMD_USER_DIR/gnome-remote-desktop-headless.service.d/override.conf"

  # Gallium driver drop-in. The static unit ships
  # `Environment="GALLIUM_DRIVER=d3d12"` because that's the fast path on
  # NVIDIA — Mesa → D3D12 → DXG → nvidia.dll, ~GL 4.6 hardware. On Intel
  # iGPUs (Meteor Lake Arc Xe) the same path renders into a broken
  # surface: mutter starts, RDP captures, but the framebuffer is never
  # painted — client sees a black screen with only the cursor visible.
  # `LIBGL_ALWAYS_SOFTWARE` is also forced when not on d3d12 so any code
  # path inside mutter that bypasses GALLIUM_DRIVER (e.g. a llvm-loaded
  # DRI driver probe) still lands on the software rasterizer.
  local gallium dropin
  gallium="$(pick_gallium_driver)"
  dropin="$SYSTEMD_USER_DIR/gnome-shell-headless.service.d/10-gpu.conf"
  if [ "$gallium" = "d3d12" ]; then
    # Default matches the static unit; remove any stale drop-in from a
    # previous Intel-detected install so the unit reverts to its baseline.
    rm -f "$dropin"
  else
    cat > "$dropin" <<EOF
# Generated by install.sh — overrides the unit's GALLIUM_DRIVER=d3d12 on
# hosts where the d3d12 path is broken (Intel Arc Xe / Meteor Lake) or
# where the user explicitly requested a fallback via
# WSL_RDP_GALLIUM_DRIVER. The unit's own Environment= line is read first;
# this drop-in is read after and wins.
[Service]
Environment="GALLIUM_DRIVER=$gallium"
Environment="LIBGL_ALWAYS_SOFTWARE=1"
Environment="MESA_LOADER_DRIVER_OVERRIDE=$gallium"
EOF
  fi

  ui_ok "Write unit files"
  ui_detail "$SYSTEMD_USER_DIR (gallium driver: $gallium)"

  ui_spin "Reload user manager + reset-failed" bash -c '
    systemctl --user daemon-reload
    systemctl --user reset-failed \
      gnome-shell-headless.service \
      gnome-remote-desktop-headless.service \
      pipewire-pulse.socket 2>/dev/null || true
  '

  # wsl-qol's install_wslg_pulse_detach already enabled
  # wslg-pulse-detach.service earlier in this run (see
  # bootstrap_wsl_qol). It runs `Before=pipewire-pulse.socket` and
  # is a no-op on a UID-1000 distro, so nothing else to do here.

  # PipeWire + WirePlumber are required by gnome-remote-desktop for screen
  # capture. They auto-start on graphical login but NOT in a headless + linger
  # setup, so enable + start them explicitly. Without them the RDP handshake
  # completes and the session dies at video-stream init — Windows reports
  # error 0x904 "session ended". pipewire-pulse handles RDP audio.
  ui_spin "Enable pipewire + wireplumber" \
    systemctl --user enable --now \
      pipewire.socket \
      pipewire-pulse.socket \
      wireplumber.service

  # gnome-keyring-daemon.socket — same kind of "auto-on at graphical login,
  # not on headless+linger" gap. The package was installed by install_packages
  # because Fedora's xdg-desktop-portal config declares
  # `org.freedesktop.impl.portal.Secret=gnome-keyring;`. Without the socket
  # enabled, the daemon never gets dbus-activated on this headless setup, the
  # portal hangs in `activating start` waiting for the Secret backend
  # (timing out every 45s in a crashloop), and every Firefox/Nautilus call
  # that hits the portal blocks the full timeout — making the whole session
  # feel frozen. Enabling the socket here closes the gap; the daemon
  # itself starts on first dbus access (which the socket file path catches).
  ui_spin "Enable gnome-keyring socket (Secret backend for portal)" \
    systemctl --user enable --now gnome-keyring-daemon.socket

  # rtkit-daemon mask is done early in install_packages (right after
  # the dnf install) so it's masked BEFORE anything can dbus-trigger
  # its spawn — see install_packages for the rationale.

  # The upstream gnome-remote-desktop-headless.service has
  # `WantedBy=gnome-session.target` in its [Install] section, so a plain
  # `systemctl --user enable` only links it into gnome-session.target.wants/.
  # We don't run gnome-session in this headless stack (gnome-shell is launched
  # directly with --mode=user), so that target never activates and grd never
  # autostarts on boot — RDP only comes up because we restart it manually
  # below. Use add-wants to additionally link it into default.target.wants/
  # so it comes up alongside gnome-shell-headless.
  ui_spin "Enable + restart RDP services" bash -c '
    systemctl --user enable    gnome-shell-headless.service              >/dev/null
    systemctl --user enable    gnome-remote-desktop-headless.service     >/dev/null
    systemctl --user add-wants default.target gnome-remote-desktop-headless.service >/dev/null
    systemctl --user restart gnome-shell-headless.service
    systemctl --user restart gnome-remote-desktop-headless.service
  '
}
